<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cat Gallery</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/CSS/styles.css">
</head>
<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="index.html">MY FAVORITE CATS</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="about.html">About</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--- Navigation Bar end --->




<!-- Gallery Section -->
<div class="container mt-4">
    <h1 class="text-center">Welcome to my favorite cats!!</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img src="/static/Images/MauDeCat.JPG" class="card-img-top" alt="Mauricio">
                <div class="card-body">
                    <h5 class="card-title">Mauricio Cat</h5>
                    <p class="card-text">Breed: Tabby Cat</p>
                    <p class="card-text">Age: 2.5</p>
                    <a href="MauDeCat.html" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div class="card">
                <img src="/static/Images/LunaDeCat.JPG" class="card-img-top" alt="Luna">
                <div class="card-body">
                    <h5 class="card-title">Luna Cat</h5>
                    <p class="card-text">Breed: Tuxedo Cat</p>
                    <p class="card-text">Age: 1</p>
                    <a href="LunaDeCat.Html" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div class="card">
                <img src="/static/Images/MangoDeCat.png" class="card-img-top" alt="Mango">
                <div class="card-body">
                    <h5 class="card-title">Mango Cat</h5>
                    <p class="card-text">Breed: Cow Cat</p>
                    <p class="card-text">Age: 8 months</p>
                    <a href="MangoDeCat.html" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div class="card">
                <img src="/static/Images/PaisleyDeCat.png" class="card-img-top" alt="Paisley">
                <div class="card-body">
                    <h5 class="card-title">Paisley Cat</h5>
                    <p class="card-text">Breed: White cat</p>
                    <p class="card-text">Age: 20</p>
                    <a href="PaisleyDeCat.html" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <img src="/static/Images/ByronDeCat.png" class="card-img-top" alt="Byron">
                <div class="card-body">
                    <h5 class="card-title">Byron Cat</h5>
                    <p class="card-text">Breed: Organe Cat </p>
                    <p class="card-text">Age: 2 </p>
                    <a href="ByronDeCat.html" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <img src="/static/Images/TamborDeCat.JPG" class="card-img-top" alt="Tambor">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <p class="card-text">Breed: Grey Cat </p>
                    <p class="card-text">Age: 9 months</p>
                    <a href="TamborDeCat.html" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>
